# Generated by Django 3.0.8 on 2020-07-18 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverallSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terranSentimentCount', models.IntegerField(null=True)),
                ('terranSentimentOverall', models.FloatField(null=True)),
                ('zergSentimentCount', models.IntegerField(null=True)),
                ('zergSentimentOverall', models.FloatField(null=True)),
                ('protossSentimentCount', models.IntegerField(null=True)),
                ('protossSentimentOverall', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchSingular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('curRace', models.CharField(blank=True, max_length=20)),
                ('uniqueID', models.IntegerField()),
                ('compoundSentiment', models.FloatField()),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('messageSentiments', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
            ],
        ),
    ]
